#!/bin/sh

. /etc/rc.subr

name="pam" # How the service will be invoked from service
rcvar="${name}_enable" # The variable in rc.conf that will allow this service to run
load_rc_config $name # Loads the config file, if relevant.

export JRE_HOME="/usr/local"

pidfile="/home/ericmiller/myservice/myservice.pid"
start_cmd="/home/ericmiller/myservice/start ; echo PAM is now running on PID $(cat $pidfile)"
stop_cmd="/home/ericmiller/myservice/stop ; echo PAM is not running. ; rm $(cat $pidfile)"
status_cmd="if [ -e $pidfile ]; then echo PAM is running on PID $(cat $pidfile). ; return 1; fi; echo MyService is not running. ; return 0"

run_rc_command "$1"

